spring.application.name=social

#Configuracion postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/social
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

#Configuracion jpa

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true